/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddEquipment: typeof import('./src/components/booking/AddEquipment.vue')['default']
    AddLiftTicket: typeof import('./src/components/booking/AddLiftTicket.vue')['default']
    AddLiftTickets: typeof import('./src/components/booking/AddLiftTickets.vue')['default']
    AddSkipackage: typeof import('./src/components/booking/AddSkipackage.vue')['default']
    AppHeader: typeof import('./src/components/core/AppHeader.vue')['default']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavForm: typeof import('bootstrap-vue-next')['BNavForm']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BookingSummary: typeof import('./src/components/booking/BookingSummary.vue')['default']
    BOverlay: typeof import('bootstrap-vue-next')['BOverlay']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTfoot: typeof import('bootstrap-vue-next')['BTfoot']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    Copy: typeof import('./src/components/booking/AddSkipackage - Copy.vue')['default']
    Header: typeof import('./src/components/core/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkipackageList: typeof import('./src/components/skiPackage/SkipackageList.vue')['default']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
  }
}
